### ISSUE TITLE
Malware Warning

### ISSUE THREAD

**Issue by ud4yk** [NxRoot/SynapseKiller#1]
While there was a malware warning, I chose to ignore it trusting the script probably tackles razer invasive-ly (I'm no programmer).

Wish this was implimented for Chroma too. though I simply disabled it from services.msc

**Comment by Noisec** [comment]
I don't really know why he didn't include the source code, but here it is:
[C74F.tmp - Copy.zip](https://github.com/user-attachments/files/16402696/C74F.tmp.-.Copy.zip)

**Comment by NxRoot** [comment]
That source code is from the old version, no longer applies to new version as it was made in a different language.
