### ISSUE TITLE
Synapse 4

### ISSUE THREAD

**Issue by jaysamuels** [NxRoot/SynapseKiller#2]
For Synapse 4, the following config has worked for me except for "GameManagerService3." This one doesn't get disabled even when specified with a config.txt file. I also am unsure if "Synapse-Boot.exe" is working as intended with Synapse 4, can you verify this as well? Here is my config for anyone else using 4 and if you'd like to update the README. I can submit a pull request if you'd like for this:

C:\Program Files\Razer\RazerAppEngine\RazerAppEngine
C:\Program Files (x86)\Razer\Razer Services\GMS3\GameManagerService3
C:\Program Files (x86)\Razer\Razer Services\GMS3\GMSServiceRegister
C:\Program Files\Razer\RazerAppEngine\app-4.0.406\CommonDLL\RzEngineMon
C:\Program Files\Razer\RazerAppEngine\app-4.0.406\CommonDLL\rzNotification
C:\Program Files\Razer\RazerAppEngine\app-4.0.406\CommonDLL\RzPowerTool

**Comment by NxRoot** [comment]
Hey there @jasamuels, the first line of the custom config file must be pointing to the the '**Razer Central**' service.

`config.txt`
```
C:\Program Files (x86)\Razer\Razer Services\Razer Central\Razer Central
C:\PATH_TO_YOUR_OTHER_SERVICE_1
C:\PATH_TO_YOUR_OTHER_SERVICE_2
C:\PATH_TO_YOUR_OTHER_SERVICE_3
```

#### HOW TO USE:
1 - You should copy the example config provided in the [README.md](https://github.com/NxRoot/SynapseKiller) of this project and add the rest of the services you need.
2 - The config file must be in the same folder as the executable that you are going to run.
